[project]
name = "gen-ai-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "langchain-groq>=0.3.6",
    "mcp-use>=1.3.7",
    "mcp[cli]>=1.12.1",
]
