version: '3.8'

services:
  banking-fraud-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-fraud-detection
    restart: unless-stopped
    
    # Environment variables
    environment:
      - MCP_SERVER_NAME=banking-fraud-detection
      - DATABASE_PATH=/app/data/bank.db
      - PYTHONPATH=/app
      
    # Volume mounts for persistent data
    volumes:
      - fraud_data:/app/data
      - ./logs:/app/logs
      
    # Port mapping (for future HTTP endpoints)
    ports:
      - "6277:6277"
      
    # Health check
    healthcheck:
      test: ["CMD", "uv", "run", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
          
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a monitoring service
  monitoring:
    image: prom/prometheus:latest
    container_name: fraud-monitoring
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    profiles:
      - monitoring

volumes:
  fraud_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  default:
    name: fraud-detection-network
    driver: bridge
