version: '3.8'

services:
  fraud-detection:
    build: .
    container_name: banking-fraud-mcp
    volumes:
      - fraud_data:/app/data
      - fraud_models:/app/models
      - fraud_logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - MCP_SERVER_NAME=banking-fraud-detection
      - DATABASE_PATH=/app/data/bank.db
      - ML_MODELS_PATH=/app/models
      - LOG_LEVEL=INFO
      - FRAUD_THRESHOLD=0.5
      - ANOMALY_THRESHOLD=-0.1
      - ML_ENABLED=true
      - OPENMP_NUM_THREADS=2
    ports:
      - "6277:6277"
    healthcheck:
      test: ["CMD", "uv", "run", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    networks:
      - fraud-net

  # Optional: Monitoring service for ML metrics
  monitoring:
    image: prom/prometheus:latest
    container_name: fraud-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - fraud-net
    profiles: 
      - monitoring

volumes:
  fraud_data:
    driver: local
  fraud_models:
    driver: local
  fraud_logs:
    driver: local
  prometheus_data:
    driver: local

networks:
  fraud-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
